/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotelbooking;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author KelvinCi
 */
public class IBienvenida extends javax.swing.JFrame {

    /**
     * Creates new form IHotelReservation
     */
    public IBienvenida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        veropciones = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 41, -1, -1));

        veropciones.setText("Ver opciones");
        veropciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veropcionesActionPerformed(evt);
            }
        });
        getContentPane().add(veropciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, -1));

        jLabel1.setText("Bienvenido a MetroHotel");
        jLabel1.setMaximumSize(new java.awt.Dimension(50, 50));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 160, 36));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void veropcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veropcionesActionPerformed
        System.out.println("Boton 'ver opciones' presionado");
        this.setVisible(false);
        IHome nuevaVentana=new IHome();
        nuevaVentana.setVisible(true);
        
        //ventanaCI.setLocationRelativeTo(true);
        //u.setLocationRelativeTo(null);
    }//GEN-LAST:event_veropcionesActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton veropciones;
    // End of variables declaration//GEN-END:variables
}
