/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotelbooking;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author KelvinCi
 */
public class IHotelReservation extends javax.swing.JFrame {

    /**
     * Creates new form IHotelReservation
     */
    public IHotelReservation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 41, -1, -1));

        jButton1.setText("Busqueda de Archivo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, -1, -1));

        jLabel1.setText("Bienvenido a MetroHotel");
        jLabel1.setMaximumSize(new java.awt.Dimension(50, 50));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 140, 36));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();//Abre el cuadro de dialogo para que el usuario seleccione los archivos 
        fc.showOpenDialog(null);//Aqui se abre la ventana y se marca null para especificar que no tenga nada seleccionado
        File archivo = fc.getSelectedFile();//Almacena el archivo elegido por el usuario 
        //Se pasa a usar try-catch porque puede que marque algun error 
        
        try {
            FileReader elquelee = new FileReader(archivo);//El encargado de leer los archivos
            BufferedReader memoryspace = new BufferedReader(elquelee);//El bufferedReader se encarga de hacer un espacio de memoria
            //para que la informacion que lea la tenga en la memoria y luego la presente donde se quiere mostrar
            String texto = "";
            String linea = "";
            while (((linea = memoryspace.readLine()) != null)) {
                texto += linea + "\n";
            }
            if (texto.isEmpty()) {
                System.out.println("Archivo sin texto");
                //textfiel.setText(texto);
            } else {
                System.out.println(texto);// o sustituir por una variable O EDDs
                JOptionPane.showMessageDialog(null, "Archivo leído con éxito");
            }

        } catch (IOException e) {
            String mensaje = "Se obtuvo un error: " + e.getMessage();
            JOptionPane.showMessageDialog(null, mensaje);
        }
        BuscarCI ventanaCI=new BuscarCI();
        this.setVisible(false);
        ventanaCI.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
